### ISSUE TITLE
Timers for master ca's

### ISSUE THREAD

**Issue by Maximtj** [Mantic-says-hi/arceuus-timers#18]
Hello, could it be it does not correctly time when the thrall despawns because of the master ca's that were updated today(gm thrall lengt for masters)  

yo

**Comment by Mantic-says-hi** [comment]
Hi Maximtj, thank you for lettimg me know. This issue should be fixed now : [https://github.com/runelite/plugin-hub/pull/8288]
an update has been approved for the plugin.

Let me know if it is working or not, I don't have a masters account to test on but it should be in runelite now, restart your client if the plugin does not show version 2.0.1, check the plugin in the Plugin Hub and press Update if it is not updated already from a client restart.

![Image](https://github.com/user-attachments/assets/98cdce3b-a1c0-4f89-a897-15d9cce8003a)

Thanks :)

**Comment by Maximtj** [comment]
hi thanks for the fast reply, ive just checked and i have the version you shared 2.0.1 ive just restarted my pc to try this (it was shut of) and can confirm its still showing the warning to cast thrall about 25 seconds,before the thrall despawns. want me to try remove the plugin and reinstall or? be happy to help you in whatever way i can.
cheers

![Image](https://github.com/user-attachments/assets/3d136047-127f-49aa-a678-65f7411a6dc2)

**Comment by Maximtj** [comment]
you can see it better on this pic 


![Image](https://github.com/user-attachments/assets/17201d45-b895-4644-ac0a-6903257bb78c)

**Comment by Maximtj** [comment]
sorry, ive mistaken another pluggin for urs.. its the spell reminder that's fucked :p the timers are actually correct ! my bad and thanks again

**Comment by Mantic-says-hi** [comment]
All good brother, they are similar plugins.
